---
title: "Automated report"
date: "23rd March 2018"
output: word_document
---

```{r setup, include=FALSE}
require("knitr")
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```


```{r}
library(tidyverse)
library(incidence)
library(openxlsx)
linelist <- openxlsx::read.xlsx("../data/MERS-CoV-cases-rok-21Jul15.xlsx",startRow=4)

##Convert all columns containing the String "...Date..." to the Date class
##using the date/month/Year format (in which the data are available)
linelist <- linelist %>%
  mutate_if(grepl("Date",names(linelist)), as.Date, format="%d/%m/%Y")

```

# Plots

### Number of cases by date of symptoms onset
```{r pressure, echo=FALSE}
inc <- incidence::incidence(linelist$Date.of.symptoms.onset, interval = 1)
plot(inc) + xlab("Date of symptoms onset") + ylab("Number of cases")
```

### Number of cases by age groups
```{r, echo=FALSE}
linelist$Age <- as.numeric(linelist$Age)
linelist$agegroup <- cut(linelist$Age,breaks= seq(min(linelist$Age), max(linelist$Age), 10))
ggplot(data=subset(linelist, !is.na(agegroup)))+
  geom_histogram(aes(x=agegroup), stat="count")+
  labs(x="Age group",y="Number of cases")

```

# Tables

### 2X2 table for status vs gender
```{r}
library(kableExtra)

table2by2 <- table(linelist$Sex, linelist$Status)
kable(table2by2)


```

